//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELKServiceStatus.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("elasticsearch-9.0.3")]
        public string esServiceName {
            get {
                return ((string)(this["esServiceName"]));
            }
            set {
                this["esServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kibana-9.0.3")]
        public string kbServiceName {
            get {
                return ((string)(this["kbServiceName"]));
            }
            set {
                this["kbServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elastic Agent")]
        public string fsServiceName {
            get {
                return ((string)(this["fsServiceName"]));
            }
            set {
                this["fsServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("logstash-9.0.3")]
        public string lsServiceName {
            get {
                return ((string)(this["lsServiceName"]));
            }
            set {
                this["lsServiceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ELK\\elk-log\\elk-xyperia.log")]
        public string esLog {
            get {
                return ((string)(this["esLog"]));
            }
            set {
                this["esLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ELK\\kibana-9.0.3\\logs\\kibana.log")]
        public string kbLog {
            get {
                return ((string)(this["kbLog"]));
            }
            set {
                this["kbLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-9.0.3-5f1479\\logs\\elastic-agent" +
            "-20250708-6.ndjson")]
        public string fsLog {
            get {
                return ((string)(this["fsLog"]));
            }
            set {
                this["fsLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\ELK\\logstash-9.0.3\\logs\\logstash.log")]
        public string lsLog {
            get {
                return ((string)(this["lsLog"]));
            }
            set {
                this["lsLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int logMaxLines {
            get {
                return ((int)(this["logMaxLines"]));
            }
            set {
                this["logMaxLines"] = value;
            }
        }
    }
}
